#configuration for makefile
#So that makefile stays largely despite the same despite the libraries being used

#High-level libraries used
#Must specify both the sub-folder levels
#and the files themselves
#	eg. HL_LIBS += blargh.c

#HL_LIBS += usbSerial.c




#HL_LIBS += $(ROOT)configuration.c

#HL_LIBS += $(LOWLEVEL)/usbhid-target.c
#HL_LIBS += $(LOWLEVEL)/usb.c

#general things
#HL_LIBS += $(MIDLEVEL)/commandHandler.c


#add a subfolder
#SUBHIGH += $(HIGHLEVEL)/folder
#HL_LIBS += $(HIGHLEVEL)/folder/blargh.c
